### ISSUE TITLE
robotics_spot repo is unavailable

### ISSUE THREAD

**Issue by sskorol** [SoftServeSAG/robotics_spot#15]
Hi @tarasborov,

There's a link to `https://github.com/tarasborov/robotics_spot.git` mentioned in README. However, it's unavailable for cloning. Is it a private repo or you've just renamed it?

Anyway, would be greatly appreciated if you could share a valid link.

Thanks,
Sergey

**Comment by sskorol** [comment]
Or there should be a reference to the current repo https://github.com/SoftServeSAG/robotics_spot.git? At least I can see docker/ros_melodic folders here.

**Comment by tarasborov** [comment]
Hi @sskorol,

Thanks for your interest in our repo for Spot simulation. This repo is deprecated. Please find the valid one https://github.com/SoftServeSAG/spot_simulation

**Comment by sskorol** [comment]
Thanks, will try! FYI, I found a link to the current repo here https://www.softserveinc.com/en-us/blog/spot-simulation-tools. So it might be helful for other people to update the link in the article if it's deprecated.

**Comment by tarasborov** [comment]
Thanks for letting us know!

**Comment by sskorol** [comment]
Found an issue with a docker image in the new repo. Will file it there. Thanks again.
